export { default as Page1 } from './Page1'
export { default as Labs } from './Labs'
export { default as Others } from './Others'
export { default as Login } from './Login'
export { default as ChangePassword } from './ChangePassword'
export { default as ProtectedRoutes } from './ProtectedRoutes'
export { default as Attendance} from './AttendanceForm'
export { default as ViewAttendance} from './ViewAttendance'
export {default as ViewTimetable} from './ViewTimetable'
export {default as Admin} from './Admin'
export {default as AddUser} from './AddUser'
export {default as AddTimetable} from './AddTimetable'
export {default as ToDoList} from './ToDoList'
export {default as DeleteUser} from './DeleteUser'
export { default as FileUpload} from './FileUpload'
export { default as ListGenerator} from './ListGenerator'